# Generated by Django 4.0.5 on 2022-06-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Last edited')),
            ],
            options={
                'ordering': ['edited', 'created'],
            },
        ),
    ]
